# Generated by Django 4.1.5 on 2023-01-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KanbanBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="KanbanList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.IntegerField()),
                ("title", models.CharField(max_length=20)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kanban.kanbanboard",
                    ),
                ),
            ],
            options={
                "ordering": ["board", "ordinal"],
            },
        ),
        migrations.CreateModel(
            name="KanbanCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kanban.kanbanlist",
                    ),
                ),
            ],
            options={
                "ordering": ["list", "ordinal"],
            },
        ),
        migrations.AddConstraint(
            model_name="kanbanlist",
            constraint=models.UniqueConstraint(
                fields=("board", "ordinal"), name="UNIQUE__KanbanList__board_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="kanbancard",
            constraint=models.UniqueConstraint(
                fields=("list", "ordinal"), name="UNIQUE__KanbanCard__list_ordinal"
            ),
        ),
    ]
