# Generated by Django 4.1.5 on 2023-01-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kanbancard",
            options={"ordering": ["kanban_list", "ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="kanbanlist",
            options={"ordering": ["kanban_board", "ordinal"]},
        ),
        migrations.RemoveConstraint(
            model_name="kanbancard",
            name="UNIQUE__KanbanCard__list_ordinal",
        ),
        migrations.RemoveConstraint(
            model_name="kanbanlist",
            name="UNIQUE__KanbanList__board_ordinal",
        ),
        migrations.RenameField(
            model_name="kanbancard",
            old_name="list",
            new_name="kanban_list",
        ),
        migrations.RenameField(
            model_name="kanbanlist",
            old_name="board",
            new_name="kanban_board",
        ),
        migrations.RemoveField(
            model_name="kanbanboard",
            name="slug",
        ),
        migrations.AddConstraint(
            model_name="kanbancard",
            constraint=models.UniqueConstraint(
                fields=("kanban_list", "ordinal"),
                name="UNIQUE__KanbanCard__kanbanlist_ordinal",
            ),
        ),
        migrations.AddConstraint(
            model_name="kanbanlist",
            constraint=models.UniqueConstraint(
                fields=("kanban_board", "ordinal"),
                name="UNIQUE__KanbanList__kanbanboard_ordinal",
            ),
        ),
    ]
