# Generated by Django 4.1.5 on 2023-01-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_alter_kanbancard_options_alter_kanbanlist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanbancard",
            name="ordinal",
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name="kanbanlist",
            name="ordinal",
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AddConstraint(
            model_name="kanbanboard",
            constraint=models.CheckConstraint(
                check=models.Q(("title__length__gt", 0)),
                name="CHECK__KanbanBoard_title__length_GT_0",
            ),
        ),
    ]
