# Generated by Django 4.1.5 on 2023-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_kanbanboard_check__kanbanboard_title__length_lte_30"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanbanlist",
            name="ordinal",
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
