# Generated by Django 4.1.5 on 2023-01-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0005_alter_kanbanlist_ordinal"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kanbanlist",
            constraint=models.CheckConstraint(
                check=models.Q(("title__length__lte", 20)),
                name="CHECK__KanbanList_title__length_LTE_20",
            ),
        ),
    ]
