# Generated by Django 4.1.5 on 2023-01-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0006_kanbanlist_check__kanbanlist_title__length_lte_20"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kanbanlist",
            constraint=models.CheckConstraint(
                check=models.Q(("title__length__gt", 0)),
                name="CHECK__KanbanList_title__length_GT_0",
            ),
        ),
    ]
